services:
  portainer:
    image: portainer/portainer-ee:2.21.5
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  portainer-agent:
    image: portainer/agent:2.21.5
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes